### ISSUE TITLE
Python example is not working 

### ISSUE THREAD

**Issue by htamas** [enablebanking/enablebanking-api-samples#24]
I'm getting the following error after installing the dependencies with pip3 in a new venv:
```
Traceback (most recent call last):
  File "/home/xx/enable_banking/jwt.py", line 9, in <module>
    import requests
  File "/home/xx/enable_banking/enable_banking/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/xx/enable_banking/enable_banking/lib/python3.12/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/xx/enable_banking/enable_banking/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/xx/enable_banking/enable_banking/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

**Comment by htamas** [comment]
Looks like it's an issue with linux
